### POST create Report
POST http://localhost:3000/reports
content-Type: application/json

{
"make": "Toyota",
"model": "Corolla",
"year": 2020,
"mileage": 15000,
"lat": 34.0522,
"lng": -118.2437,
"price": 20000
}

### PATCH Report for Approval
PATCH http://localhost:3000/reports/3
content-Type: application/json

{
  "approved": false
}


### GET all Reports
GET localhost:3000
content-Type: application/json
