### Create new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "1@c.zzz",
  "password": "123456"
}

### Get User By ID
GET http://localhost:3000/auth/1

### Post Signup User
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "5@ccc.com",
  "password": "123456"
}

### Post SignIn User
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "5@ccc.com",
  "password": "123456"
}

### GET Who Am I
GET http://localhost:3000/auth/whoami
content-type: application/json

### GET Who Am I
GET http://localhost:3000/auth/new
content-type: application/json
